function f_total = pffAttacker(dball,dshotpath,dshotpathDef,dgoalAtt,dgoalDef,dbehindball,in7,in8)
%PFFATTACKER
%    F_TOTAL = PFFATTACKER(DBALL,DSHOTPATH,DSHOTPATHDEF,DGOALATT,DGOALDEF,DBEHINDBALL,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Oct-2016 15:14:55

dmate1 = in8(:,1);
dmate2 = in8(:,2);
dmate3 = in8(:,3);
dmate4 = in8(:,4);
dside1 = in7(:,1);
dside2 = in7(:,2);
dside3 = in7(:,3);
dside4 = in7(:,4);
t2 = dshotpath-1.0./1.0e1;
t3 = 1.0./dmate1-2.0;
t4 = 1.0./dmate2-2.0;
t5 = 1.0./dmate3-2.0;
t6 = 1.0./dmate4-2.0;
t7 = 1.0./dside1-5.0;
t8 = 1.0./dside2-5.0;
t9 = 1.0./dside3-5.0;
t10 = 1.0./dside4-5.0;
f_total = dball.^2.*(heaviside(dball-1.0e1).*(1.0./2.0)-heaviside(dball).*(1.0./2.0)).*-5.0-dbehindball.^2.*(heaviside(dbehindball-1.0).*(1.0./2.0)-heaviside(dbehindball).*(1.0./2.0)).*9.0e1-t3.^2.*(heaviside(dmate1-1.0./2.0).*(1.0./2.0)-heaviside(dmate1).*(1.0./2.0)).*(1.0./2.0)-t4.^2.*(heaviside(dmate2-1.0./2.0).*(1.0./2.0)-heaviside(dmate2).*(1.0./2.0)).*(1.0./2.0)-t5.^2.*(heaviside(dmate3-1.0./2.0).*(1.0./2.0)-heaviside(dmate3).*(1.0./2.0)).*(1.0./2.0)-t6.^2.*(heaviside(dmate4-1.0./2.0).*(1.0./2.0)-heaviside(dmate4).*(1.0./2.0)).*(1.0./2.0)-t7.^2.*(heaviside(dside1-1.0./5.0).*(1.0./2.0)-heaviside(dside1).*(1.0./2.0))-t8.^2.*(heaviside(dside2-1.0./5.0).*(1.0./2.0)-heaviside(dside2).*(1.0./2.0))-t9.^2.*(heaviside(dside3-1.0./5.0).*(1.0./2.0)-heaviside(dside3).*(1.0./2.0))-t10.^2.*(heaviside(dside4-1.0./5.0).*(1.0./2.0)-heaviside(dside4).*(1.0./2.0))-t2.^2.*(heaviside(dshotpath-1.0e1).*(1.0./2.0)-heaviside(dshotpath).*(1.0./2.0)).*2.0e1;
