function f_total = pffAttacker(dball,dshotpath,dshotpathDef,dgoalAtt,dgoalDef,in6,in7)
%PFFATTACKER
%    F_TOTAL = PFFATTACKER(DBALL,DSHOTPATH,DSHOTPATHDEF,DGOALATT,DGOALDEF,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Oct-2016 07:53:55

dmate1 = in7(:,1);
dmate2 = in7(:,2);
dside1 = in6(:,1);
dside2 = in6(:,2);
dside3 = in6(:,3);
dside4 = in6(:,4);
t2 = dball+3.568125444059277e-1;
t3 = dgoalDef-3.395814072977423e-1;
t4 = 1.0./dside1-2.486716240744494;
t5 = 1.0./dside2-2.486716240744494;
t6 = 1.0./dside3-2.486716240744494;
t7 = 1.0./dside4-2.486716240744494;
t8 = 1.0./dmate1-5.188500583965492;
t9 = 1.0./dmate2-5.188500583965492;
t10 = dgoalAtt+1.029416297071439e-1;
t11 = dshotpath+8.768829781270573e-1;
f_total = t4.^2.*(heaviside(dside1).*(1.0./2.0)-heaviside(dside1-4.021367551372132e-1).*(1.0./2.0)).*5.257191559557773e-1+t5.^2.*(heaviside(dside2).*(1.0./2.0)-heaviside(dside2-4.021367551372132e-1).*(1.0./2.0)).*5.257191559557773e-1+t6.^2.*(heaviside(dside3).*(1.0./2.0)-heaviside(dside3-4.021367551372132e-1).*(1.0./2.0)).*5.257191559557773e-1+t7.^2.*(heaviside(dside4).*(1.0./2.0)-heaviside(dside4-4.021367551372132e-1).*(1.0./2.0)).*5.257191559557773e-1-t11.^2.*(heaviside(dshotpath-9.760087674565955).*(1.0./2.0)-heaviside(dshotpath).*(1.0./2.0)).*1.006375333588106e1-t8.^2.*(heaviside(dmate1-1.927339091163242e-1).*(1.0./2.0)-heaviside(dmate1).*(1.0./2.0)).*7.768011193041109e-1-t9.^2.*(heaviside(dmate2-1.927339091163242e-1).*(1.0./2.0)-heaviside(dmate2).*(1.0./2.0)).*7.768011193041109e-1-t2.^2.*(heaviside(dball-1.002323425577057e1).*(1.0./2.0)-heaviside(dball).*(1.0./2.0)).*1.134585066183731e1-t10.^2.*(heaviside(dgoalAtt+4.104245108978636e-1).*(1.0./2.0)-heaviside(dgoalAtt).*(1.0./2.0)).*1.102312564365192-t3.^2.*(heaviside(dgoalDef).*(1.0./2.0)-heaviside(dgoalDef-3.078793674582718e-1).*(1.0./2.0)).*7.330731194343107e-2;
