function f_total = pffDefender(dball,dshotpath,dshotpathDef,dgoalAtt,dgoalDef,dbehindball,in7,in8)
%PFFDEFENDER
%    F_TOTAL = PFFDEFENDER(DBALL,DSHOTPATH,DSHOTPATHDEF,DGOALATT,DGOALDEF,DBEHINDBALL,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    27-Oct-2016 15:14:55

dmate1 = in8(:,1);
dmate2 = in8(:,2);
dmate3 = in8(:,3);
dmate4 = in8(:,4);
dside1 = in7(:,1);
dside2 = in7(:,2);
dside3 = in7(:,3);
dside4 = in7(:,4);
t2 = dbehindball-1.0;
t3 = dgoalDef-3.0./2.0;
t4 = dshotpathDef-1.0./1.0e2;
t5 = 1.0./dmate1-1.0;
t6 = 1.0./dmate2-1.0;
t7 = 1.0./dmate3-1.0;
t8 = 1.0./dmate4-1.0;
t9 = 1.0./dside1-5.0;
t10 = 1.0./dside2-5.0;
t11 = 1.0./dside3-5.0;
t12 = 1.0./dside4-5.0;
f_total = t2.^2.*(heaviside(dbehindball-9.0).*(1.0./2.0)-heaviside(dbehindball).*(1.0./2.0)).*-3.0-t3.^2.*(heaviside(dgoalDef-1.0e1).*(1.0./2.0)-heaviside(dgoalDef).*(1.0./2.0)).*4.0-t5.^2.*(heaviside(dmate1-1.0).*(1.0./2.0)-heaviside(dmate1).*(1.0./2.0)).*(1.0./2.0)-t6.^2.*(heaviside(dmate2-1.0).*(1.0./2.0)-heaviside(dmate2).*(1.0./2.0)).*(1.0./2.0)-t7.^2.*(heaviside(dmate3-1.0).*(1.0./2.0)-heaviside(dmate3).*(1.0./2.0)).*(1.0./2.0)-t8.^2.*(heaviside(dmate4-1.0).*(1.0./2.0)-heaviside(dmate4).*(1.0./2.0)).*(1.0./2.0)-t9.^2.*(heaviside(dside1-1.0./5.0).*(1.0./2.0)-heaviside(dside1).*(1.0./2.0))-t10.^2.*(heaviside(dside2-1.0./5.0).*(1.0./2.0)-heaviside(dside2).*(1.0./2.0))-t11.^2.*(heaviside(dside3-1.0./5.0).*(1.0./2.0)-heaviside(dside3).*(1.0./2.0))-t12.^2.*(heaviside(dside4-1.0./5.0).*(1.0./2.0)-heaviside(dside4).*(1.0./2.0))-t4.^2.*(heaviside(dshotpathDef-9.0).*(1.0./2.0)-heaviside(dshotpathDef).*(1.0./2.0)).*2.0;
