function f_total = pffGoalie(dball,dshotpath,dgoal,in4,in5)
%PFFGOALIE
%    F_TOTAL = PFFGOALIE(DBALL,DSHOTPATH,DGOAL,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    07-Oct-2016 14:20:37

t2 = dball-1.0e1;
t3 = dgoal-2.0;
t4 = dshotpath-1.0;
f_total = -t2.^2.*(heaviside(dball-1.0./5.0).*(1.0./2.0)-heaviside(dball).*(1.0./2.0))-t3.^2.*(heaviside(dgoal-1.0).*(1.0./2.0)-heaviside(dgoal).*(1.0./2.0)).*4.0-t4.^2.*(heaviside(dshotpath-4.0).*(1.0./2.0)-heaviside(dshotpath).*(1.0./2.0));
