function f_total = pffGeneral1(dball,dshotpath,dshotpathDef,dgoalAtt,dgoalDef,dbehindball,in7,dmate1,in9)
%PFFGENERAL1
%    F_TOTAL = PFFGENERAL1(DBALL,DSHOTPATH,DSHOTPATHDEF,DGOALATT,DGOALDEF,DBEHINDBALL,IN7,DMATE1,IN9)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Dec-2016 12:29:32

dside1 = in7(:,1);
dside2 = in7(:,2);
dside3 = in7(:,3);
dside4 = in7(:,4);
weights1 = in9(1,:);
weights2 = in9(2,:);
weights3 = in9(3,:);
weights4 = in9(4,:);
weights5 = in9(5,:);
weights6 = in9(6,:);
weights7 = in9(7,:);
weights8 = in9(8,:);
weights9 = in9(9,:);
weights10 = in9(10,:);
weights11 = in9(11,:);
weights12 = in9(12,:);
weights13 = in9(13,:);
weights14 = in9(14,:);
weights15 = in9(15,:);
weights16 = in9(16,:);
weights17 = in9(17,:);
weights18 = in9(18,:);
weights19 = in9(19,:);
weights20 = in9(20,:);
weights21 = in9(21,:);
t3 = 1.0./weights19;
t2 = t3-1.0./(dside1-weights20);
t4 = t3-1.0./(dside2-weights20);
t5 = t3-1.0./(dside3-weights20);
t6 = t3-1.0./(dside4-weights20);
t7 = dball-weights2;
t8 = dbehindball-weights17;
t9 = dgoalDef-weights14;
t10 = dgoalAtt-weights11;
t11 = dshotpath-weights5;
t12 = dshotpathDef-weights8;
f_total = -t7.^2.*weights3.*(heaviside(dball-weights1).*(1.0./2.0)-heaviside(dball).*(1.0./2.0))-t8.^2.*weights18.*(heaviside(dbehindball-weights16).*(1.0./2.0)-heaviside(dbehindball).*(1.0./2.0))-t9.^2.*weights15.*(heaviside(dgoalDef-weights13).*(1.0./2.0)-heaviside(dgoalDef).*(1.0./2.0))-t10.^2.*weights12.*(heaviside(dgoalAtt-weights10).*(1.0./2.0)-heaviside(dgoalAtt).*(1.0./2.0))-t2.^2.*weights21.*(heaviside(dside1-weights19).*(1.0./2.0)-heaviside(dside1).*(1.0./2.0))-t4.^2.*weights21.*(heaviside(dside2-weights19).*(1.0./2.0)-heaviside(dside2).*(1.0./2.0))-t5.^2.*weights21.*(heaviside(dside3-weights19).*(1.0./2.0)-heaviside(dside3).*(1.0./2.0))-t6.^2.*weights21.*(heaviside(dside4-weights19).*(1.0./2.0)-heaviside(dside4).*(1.0./2.0))-t11.^2.*weights6.*(heaviside(dshotpath-weights4).*(1.0./2.0)-heaviside(dshotpath).*(1.0./2.0))-t12.^2.*weights9.*(heaviside(dshotpathDef-weights7).*(1.0./2.0)-heaviside(dshotpathDef).*(1.0./2.0));
