function f_total = pffGoalie(dball,dshotpath,dshotpathDef,dgoalAtt,dgoalDef,in6,in7)
%PFFGOALIE
%    F_TOTAL = PFFGOALIE(DBALL,DSHOTPATH,DSHOTPATHDEF,DGOALATT,DGOALDEF,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    11-Oct-2016 07:53:55

t2 = dball-1.0e1;
t3 = dgoalDef-2.0;
t4 = dgoalAtt-2.0;
t5 = dshotpath-1.0;
t6 = dshotpathDef-1.0;
f_total = -t2.^2.*(heaviside(dball-1.0./5.0).*(1.0./2.0)-heaviside(dball).*(1.0./2.0))-t3.^2.*(heaviside(dgoalDef-1.0).*(1.0./2.0)-heaviside(dgoalDef).*(1.0./2.0)).*4.0-t4.^2.*(heaviside(dgoalAtt-1.0).*(1.0./2.0)-heaviside(dgoalAtt).*(1.0./2.0)).*4.0-t5.^2.*(heaviside(dshotpath-4.0).*(1.0./2.0)-heaviside(dshotpath).*(1.0./2.0))-t6.^2.*(heaviside(dshotpathDef-4.0).*(1.0./2.0)-heaviside(dshotpathDef).*(1.0./2.0));
