function f_total = pffGeneral5(dball,dshotpath,dshotpathDef,dgoalAtt,dgoalDef,dbehindball,in7,in8,in9)
%PFFGENERAL5
%    F_TOTAL = PFFGENERAL5(DBALL,DSHOTPATH,DSHOTPATHDEF,DGOALATT,DGOALDEF,DBEHINDBALL,IN7,IN8,IN9)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Dec-2016 12:29:35

dmate1 = in8(:,1);
dmate2 = in8(:,2);
dmate3 = in8(:,3);
dmate4 = in8(:,4);
dside1 = in7(:,1);
dside2 = in7(:,2);
dside3 = in7(:,3);
dside4 = in7(:,4);
weights1 = in9(1,:);
weights2 = in9(2,:);
weights3 = in9(3,:);
weights4 = in9(4,:);
weights5 = in9(5,:);
weights6 = in9(6,:);
weights7 = in9(7,:);
weights8 = in9(8,:);
weights9 = in9(9,:);
weights10 = in9(10,:);
weights11 = in9(11,:);
weights12 = in9(12,:);
weights13 = in9(13,:);
weights14 = in9(14,:);
weights15 = in9(15,:);
weights16 = in9(16,:);
weights17 = in9(17,:);
weights18 = in9(18,:);
weights19 = in9(19,:);
weights20 = in9(20,:);
weights21 = in9(21,:);
weights22 = in9(22,:);
weights23 = in9(23,:);
weights24 = in9(24,:);
t3 = 1.0./weights22;
t2 = t3-1.0./(dmate1-weights23);
t4 = t3-1.0./(dmate2-weights23);
t5 = t3-1.0./(dmate3-weights23);
t6 = t3-1.0./(dmate4-weights23);
t8 = 1.0./weights19;
t7 = t8-1.0./(dside1-weights20);
t9 = t8-1.0./(dside2-weights20);
t10 = t8-1.0./(dside3-weights20);
t11 = t8-1.0./(dside4-weights20);
t12 = dball-weights2;
t13 = dbehindball-weights17;
t14 = dgoalDef-weights14;
t15 = dgoalAtt-weights11;
t16 = dshotpath-weights5;
t17 = dshotpathDef-weights8;
f_total = -t12.^2.*weights3.*(heaviside(dball-weights1).*(1.0./2.0)-heaviside(dball).*(1.0./2.0))-t13.^2.*weights18.*(heaviside(dbehindball-weights16).*(1.0./2.0)-heaviside(dbehindball).*(1.0./2.0))-t14.^2.*weights15.*(heaviside(dgoalDef-weights13).*(1.0./2.0)-heaviside(dgoalDef).*(1.0./2.0))-t15.^2.*weights12.*(heaviside(dgoalAtt-weights10).*(1.0./2.0)-heaviside(dgoalAtt).*(1.0./2.0))-t2.^2.*weights24.*(heaviside(dmate1-weights22).*(1.0./2.0)-heaviside(dmate1).*(1.0./2.0))-t4.^2.*weights24.*(heaviside(dmate2-weights22).*(1.0./2.0)-heaviside(dmate2).*(1.0./2.0))-t5.^2.*weights24.*(heaviside(dmate3-weights22).*(1.0./2.0)-heaviside(dmate3).*(1.0./2.0))-t6.^2.*weights24.*(heaviside(dmate4-weights22).*(1.0./2.0)-heaviside(dmate4).*(1.0./2.0))-t7.^2.*weights21.*(heaviside(dside1-weights19).*(1.0./2.0)-heaviside(dside1).*(1.0./2.0))-t9.^2.*weights21.*(heaviside(dside2-weights19).*(1.0./2.0)-heaviside(dside2).*(1.0./2.0))-t10.^2.*weights21.*(heaviside(dside3-weights19).*(1.0./2.0)-heaviside(dside3).*(1.0./2.0))-t11.^2.*weights21.*(heaviside(dside4-weights19).*(1.0./2.0)-heaviside(dside4).*(1.0./2.0))-t16.^2.*weights6.*(heaviside(dshotpath-weights4).*(1.0./2.0)-heaviside(dshotpath).*(1.0./2.0))-t17.^2.*weights9.*(heaviside(dshotpathDef-weights7).*(1.0./2.0)-heaviside(dshotpathDef).*(1.0./2.0));
